[server]
headless = true
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor = "#005ea2"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#333333"
font = "sans-serif" 